# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnormdouble <- function(b, c) {
    .Call(`_MSO_rnormdouble`, b, c)
}

chooseC <- function(n, k) {
    .Call(`_MSO_chooseC`, n, k)
}

binom_mass <- function(y, psi, p, K) {
    .Call(`_MSO_binom_mass`, y, psi, p, K)
}

lbinom_mass <- function(y, psi, p, K) {
    .Call(`_MSO_lbinom_mass`, y, psi, p, K)
}

lbinom_mass_p2 <- function(y, psi, p, K) {
    .Call(`_MSO_lbinom_mass_p2`, y, psi, p, K)
}

MSOBinlogitcpp <- function(X, V, Y, z, p, psi, nsitevisits, a2, b2, A2, B2, ndraws, percent_burn_in, thin, selection) {
    .Call(`_MSO_MSOBinlogitcpp`, X, V, Y, z, p, psi, nsitevisits, a2, b2, A2, B2, ndraws, percent_burn_in, thin, selection)
}

MSOBinocclogitcpp <- function(X, V, Y, z, K, Minv, p, psi, tau_i, a_tau, b_tau, nsitevisits, a2, b2, A2, B2, ndraws, percent_burn_in, thin) {
    .Call(`_MSO_MSOBinocclogitcpp`, X, V, Y, z, K, Minv, p, psi, tau_i, a_tau, b_tau, nsitevisits, a2, b2, A2, B2, ndraws, percent_burn_in, thin)
}

